### ISSUE TITLE
cdr.py > 'numpy.ndarray' object has no attribute 'filled'

### ISSUE THREAD

**Issue by ninadel** [TUW-GEO/ascat#36]
https://github.com/TUW-GEO/ascat/blob/39548cb95e1d011bbbcc78e4de8c8c1d4e41844a/ascat/read_native/cdr.py#L232

I am trying to use this package for this pytesmo validation example: https://pytesmo.readthedocs.io/en/latest/examples.html#example-soil-moisture-validation-ascat-ismn and am getting the error 'numpy.ndarray' object has no attribute 'filled'

**Comment by ninadel** [comment]
[validation_framework_error.txt](https://github.com/TUW-GEO/ascat/files/4542214/validation_framework_error.txt)

I am using
ascat 1.0.2
netcdf4 1.2.8
pytesmo 0.8
pygeobase 0.3.18

**Comment by sebhahn** [comment]
I cannot reproduce your error. Do you have the static layer data?

**Comment by ninadel** [comment]
I am using the ISMN and ASCAT data from https://github.com/TUW-GEO/pytesmo-test-data

**Comment by sebhahn** [comment]
Could you please try to update netcdf4 to 1.4.2 or higher?

**Comment by ninadel** [comment]
Hello, I did a conda update all and my netcdf4 has been updated to 1.5.3. This resolves the above error message (although since I did an update all I can't tell if it was netcdf4 or another package). Thank you! It looks like the ascat & pytesmo installers do not require a specific version of netcdf4.
