### ISSUE TITLE
Reading h101 product (.nc version)

### ISSUE THREAD

**Issue by ninadel** [TUW-GEO/ascat#38]
Hi, I have h101 files in .nc format (from the EUMETSAT data center (https://navigator.eumetsat.int/product/EO:EUM:DAT:METOP:SOMO12) and I noticed this reader only reads h101 files in .bufr--is there a way to read this format either by modifying the h101 reader or using one of the other nc format readers?

https://github.com/TUW-GEO/ascat/blob/27f43293fab60ec6a81ba24796decd12c2e8f75b/src/ascat/h_saf.py#L388

**Comment by sebhahn** [comment]
The .nc format can be read using the netCDF4 package in python
