### ISSUE TITLE
Reading CGLS SWI Europe 1km

### ISSUE THREAD

**Issue by ninadel** [TUW-GEO/ascat#39]
Hello,
We were hoping to read the CGLS SWI Europe product since it has a higher 1km resolution. I looked at the code and it appears that at this time we can only read CGLS TS at Global resolution. Could you confirm which CGLS products could be read, since the documentation suggests we can read all CGLS products? Thank you in advance.

**Comment by sebhahn** [comment]
The documentation is not correct. Only the CGLS TS product is supported at the moment
