### ISSUE TITLE
TUW_WARP5_grid_info_2_2.nc?

### ISSUE THREAD

**Issue by ninadel** [TUW-GEO/ascat#40]
Hi, 

General questions about reading the ASCAT SSM TS products (e.g. H113Ts).
In the class it says to use TUW_WARP5_grid_info_2_2.nc while in the testdata I can only find TUW_WARP5_grid_info_2_1.nc. Are these functionally the same/interchangable, and if they aren't is this grid file available anywhere? I couldn't find it on the ftp server. 

Also are the static layers @ https://github.com/TUW-GEO/pytesmo-test-data/tree/master/sat/h_saf/static_layer intended to be used with all ASCAT products? I'm not familiar with what this is used for in terms of analysis.

**Comment by sebhahn** [comment]
The grid file and static layer files are on the H SAF FTP server. The grid file contains lon, lat, gpi, cell information, which can also be looked up here: https://www.geo.tuwien.ac.at/dgg/index.php
The new grid file version contains additional information (e.g. committed area).

The static layer files contain "static" information about topographic complexity (soil moisture retrieval in mountainous areas is problematic), frozen soil and snow cover climatology (soil moisture retrieval is hardly possible or impossible) and porosity information (to translate from saturation (%) to volumetric soil moisture (m^3 m^-3)). Please have a look at the Product User Manuel (PUM), which contains more details.

**Comment by ninadel** [comment]
Thank you! I was on the ftp server looking for grid/static but didn't realize they were under an aux folder.
