### ISSUE TITLE
Missing dependencies after install with environment.yml

### ISSUE THREAD

**Issue by serbinsh** [TUW-GEO/ascat#51]
Hello

I am exploring this package to develop a regional soil moisture dataset for the Southeast U.S. I followed the simple conda install instructions but found that doing so results in a missing dependency, matplotlib, if building a brand new env. 

![Screen Shot 2023-01-30 at 8 45 53 AM](https://user-images.githubusercontent.com/3067369/215494634-c06e77ba-d5f9-4a36-8424-b826f72256ed.png)

I am going to test that its the only missing depends then provide a quick fix

**Comment by sebhahn** [comment]
Thanks @serbinsh, but matplotlib shouldn't be part of the standard installation of the ascat package. It is used in the jupyter notebook as an example to plot the data. Maybe there should be an additional environment.yml to be installed for running the examples.

**Comment by serbinsh** [comment]
@sebhahn Ahhh...yes of course, thats my fault.  OK then we can close this, though, I do think showing how to build and run the examples, perhaps in example notebooks, would help.

**Comment by sebhahn** [comment]
I'll try to add this to the next release

**Comment by serbinsh** [comment]
Thanks!
